SAMPLES:
 - SRR19279042_SCANseq2_UMI200
 - SRR19279044_SCANseq2_UMI100
 - SRR19279045_SCANseq2_4CL
 - SRR19279047_SCANseq2_9CL
BARCODE_FASTA: data/nanopore_96_barcodes.fa
PRIMER_CONFIG: data/primer_config.txt
HUMAN_GENOME_FASTA: /home/chenzonggui/species/homo_sapiens/GRCh38.p13/GRCh38.canonical.genome.fa
HUMAN_TRANSCRIPT_BED: /home/chenzonggui/species/homo_sapiens/GRCh38.p13/gencode.v39.annotation.transcripts.bed
HUMAN_TRANSCRIPT_BED_GZ: /home/chenzonggui/species/homo_sapiens/GRCh38.p13/gencode.v39.annotation.transcripts.bed.gz
HUMAN_ANNOTATION_GTF: /home/chenzonggui/species/homo_sapiens/GRCh38.p13/gencode.v39.annotation.sorted.gtf
HUMAN_SPLICE_MMI: /home/chenzonggui/species/homo_sapiens/GRCh38.p13/GRCh38.canonical.mm2.splice.mmi
MOUSE_GENOME_FASTA: /home/chenzonggui/species/mus_musculus/GRCm38.p6/GRCm38.canonical.genome.fa
MOUSE_TRANSCRIPT_BED: /home/chenzonggui/species/mus_musculus/GRCm38.p6/gencode.vM25.annotation.transcripts.bed
MOUSE_TRANSCRIPT_BED_GZ: /home/chenzonggui/species/mus_musculus/GRCm38.p6/gencode.vM25.annotation.transcripts.bed.gz
MOUSE_ANNOTATION_GTF: /home/chenzonggui/species/mus_musculus/GRCm38.p6/gencode.vM25.annotation.sorted.gtf
MOUSE_SPLICE_MMI: /home/chenzonggui/species/mus_musculus/GRCm38.p6/GRCm38.canonical.mm2.splice.mmi
