FQDIR: data/datasets
FASTA: ../share/homo_sapiens/GRCh38.p13/GRCh38.canonical.genome.fa
GTF: ../share/homo_sapiens/GRCh38.p13/gencode.v39.annotation.sorted.gtf
TRANSCRIPT_BED_GZ: ../share/homo_sapiens/GRCh38.p13/gencode.v39.transcripts.bed.gz
TRANSCRIPT_INFO: ../share/homo_sapiens/GRCh38.p13/gencode.v39.transcript_info.added_canonical.csv
SNP_BED_GZ: ../share/homo_sapiens/hg38/snp151.3.lite.bed.gz
FASTA_RIBO: ../share/homo_sapiens/ncbi/ribosomal_rna.fasta
RUNS:
 - 20220113_NASCseq
 - 20220321_NASCseq
 - 20220418_NASCseq
 - GSE128273_NASCseq
 - GSE128273_NASCseq_SE

