SAMPLES:
 - GSM1480327_K562_PROseq # SRR1554311 and SRR1554312
 - GSM2361442_K562_PROseq_NHS_Rep1
 - GSM2361443_K562_PROseq_NHS_Rep2
 - GSM2545324_K562_PROseq_preseq_0min_plus_rep1
 - GSM2545325_K562_PROseq_preseq_0min_plus_rep2
 - GSM3452725_K562_PROseq
FQDIR: data/fastqs
FASTA: ../share/homo_sapiens/GRCh38.p13/GRCh38.canonical.genome.fa
GTF: ../share/homo_sapiens/GRCh38.p13/gencode.v39.annotation.sorted.gtf
FASTA_RIBO: ../share/homo_sapiens/ncbi/ribosomal_rna.fasta
TRANSCRIPT_BED_GZ: ../share/homo_sapiens/GRCh38.p13/gencode.v39.transcripts.bed.gz
